# Required for UniformTypeIdentifiers (-weak_framework UniformTypeIdentifiers)
MACOSX_SDK_VERSION:             # [osx and x86_64]
  - "11.0"                      # [osx and x86_64]
CONDA_BUILD_SYSROOT:            # [osx and x86_64]
  - /opt/MacOSX10.13.sdk        # [osx and x86_64]
