matrix:
- []
- [[VC_VERSION, 9], [CONDA_PY, 27]]
- [[VC_VERSION, 14], [CONDA_PY, 35]]

travis:
  secure:
    BINSTAR_TOKEN: q0vKEXYDyNeScx6TTAGyvT1N0GGhorLm02dnAs5/nvDvpKR0KLWPJdaIqbkJhrgkVXn3HTOsFvsL0cQY9b09oyXI7LNefdPmgUQMZF0K8x5S4Sg3gUq+IEFLg3mD4WFVOpNoRMngQciNIXLnmjer7srnNx1hSrI7ErfMYMqPb9ir37/TQPxQn7RX4OkiPIglyiD+MsZxtbTWJgxyxXa67JUHk2LmYLjwYNqiYxYDSYNgi+QvqomADhO4L/azvqjdoqTzfrzGyzKak+Y4vfdPTk3JbNpB4JAceFxCwG3XPGpZL33BJJIDc/7Pc0HZzpIx+tgbwUz/uxc+NtZUYOP+0+RI/wQEFiUJhGbhyD3tTP/LtxeS+DuYxMHANkHSuQze5SpOlg5G9bkeA/CHssbqbJjE1Vx5jAOXc1x4st6eQ6jcpfSnmEUTwsKQvsQYnpiU9h4MnrG+R6w6A+yTcopUdKi1l8k2fVF0CiamGjNjHoCLgwUVHtTgaIoG4fPgT8smKAWWB1zAkHiL+8DzAsSpQQY7/klXwkWcQHbEpm4VddqxA8/bW7UNWOfl7ylmkResUKoAIaHAcwZW1eww2kyOAhGP2LTgO27zfdiudyPqpVQsmqvmstqMeB/zmQ6niYSCv8WVvxIOa72FNX/KNtjOZGk/3kEEdhTuPFQeTFAnRWg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
